### PR TITLE
Fixed issue with checking flag support

### PR DESCRIPTION
**Pull request by cryptopragmatic**

### CODE REVIEW

**Comment by cryptopragmatic** [comment]
It wasn't working with latest version of github.com/klauspost/cpuid

**Comment by mholt** [comment]
This appears to be a mistake...

**Comment by cryptopragmatic** [comment]
@mholt, what does? I created a simple server using example the same way like before and it was working before and now it doesn't. I'm getting this error:

go get
# github.com/caddyserver/certmagic
../../caddyserver/certmagic/crypto.go:336:14: cpuid.CPU.AesNi undefined (type cpuid.CPUInfo has no field or method AesNi)

And it's because github.com/klauspost/cpuid changed it's library. I don't get it.

**Comment by cryptopragmatic** [comment]
This is my code:

```
package main

import (
	"github.com/caddyserver/certmagic"
	"gopkg.in/macaron.v1"
)

func main() {
	m := macaron.Classic()

	certmagic.DefaultACME.Email = "test@test.com"
	certmagic.HTTPS([]string{"www.example.com"}, m)
}
```

And this is the output.

```
go build && ./certtest 
# github.com/caddyserver/certmagic
../../caddyserver/certmagic/crypto.go:336:14: cpuid.CPU.AesNi undefined (type cpuid.CPUInfo has no field or method AesNi)
```

**Comment by mholt** [comment]
Simply because it doesn't compile. See the failed checks.

This is the function we use: https://pkg.go.dev/github.com/klauspost/cpuid#CPUInfo.AesNi

Yours appears to be using this one: https://pkg.go.dev/github.com/klauspost/cpuid/v2#CPUInfo.Supports

**Comment by cryptopragmatic** [comment]
I still don't get it. You see my code? It's the simplest possible usage of your library and it doesn't work. Out of box, error? What is the communication problem here? It's not what I'm using, it's what you're using. You're using master branch of klauspost/cpuid and it doesn't work. How much more clear can I be?

**Comment by cryptopragmatic** [comment]
Should I have used something other than include "github.com/caddyserver/certmagic"?

Admittedly, I don't really get that package / modules mess they did with go.

**Comment by cryptopragmatic** [comment]
Just doing simple plain go get with caddyserver/certmagic, I get an error, it's not hard to reproduce. No project, all clean, no old libraries or packages, just like this:

```
go get github.com/caddyserver/certmagic
# github.com/caddyserver/certmagic
../../caddyserver/certmagic/crypto.go:336:14: cpuid.CPU.AesNi undefined (type cpuid.CPUInfo has no field or method AesNi)
```

**Comment by francislavoie** [comment]
You're pulling cpuid v2 for some reason. This project uses v1.

**Comment by cryptopragmatic** [comment]
You're not listening. I'm not doing anything that's not in the Readme. Here's output from the clean server, latest version of go, new installation, never been installed.

```
anon@server1:~$ sudo tar -C /usr/local -xzf go1.15.7.linux-amd64.tar.gz
[sudo] password for anon: 
anon@server1:~$ mkdir go
anon@server1:~$ cd go
anon@server1:~/go$ go get github.com/caddyserver/certmagic
# github.com/caddyserver/certmagic
src/github.com/caddyserver/certmagic/crypto.go:336:14: cpuid.CPU.AesNi undefined (type cpuid.CPUInfo has no field or method AesNi)
anon@server1:~/go$ 
```

**Comment by cryptopragmatic** [comment]
I'd say it has something to do with latest version of go and this:

https://github.com/klauspost/cpuid/blob/master/go.mod

**Comment by cryptopragmatic** [comment]
And it was changed on December 8th 2020.

https://github.com/klauspost/cpuid/commit/4c872f36d0b12aa3c19b376252b29e12037cb127#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6

**Comment by francislavoie** [comment]
The go.sum in certmagic locks it to v1.2.5. So I'm pretty sure something you're doing is causing it to try to pull the latest version, which is not compatible.

**Comment by cryptopragmatic** [comment]
Yeah, it's me. Your tests use old version of go. I'm using the latest. Try it with the latest version. I'm not an idiot, guys.

**Comment by francislavoie** [comment]
Please don't attack us. Calm down. I'm just stating the facts. I don't know what the problem is, but there is clearly a problem, _somewhere_.

**Comment by cryptopragmatic** [comment]
From what I can see, tests use go1.14.14

I use go1.15.7, which is the latest version.

**Comment by francislavoie** [comment]
Latest test runs used 1.15.6: https://github.com/caddyserver/certmagic/runs/1773016905

**Comment by cryptopragmatic** [comment]
Can you reproduce the issue by installing latest go version and hitting go get github.com/caddyserver/certmagic?

It isn't that hard to try. I'm speechless. :)

**Comment by cryptopragmatic** [comment]
From klauspost/cpuid:

```
go get -u github.com/klauspost/cpuid/v2 using modules.
Drop v2 for others.
```

Maybe it might give you a clue.

**Comment by francislavoie** [comment]
I was on my phone until 10 minutes ago. Yes I can reproduce using `go get`. But I think that's not the correct way to use this lib because that uses GOPATH mode.

It gets pulled just fine if I `go mod init` then add `require github.com/caddyserver/certmagic v0.12.1-0.20210126230115-267fdad76a0f` then build it.

**Comment by cryptopragmatic** [comment]
So, what you want to say that what's stated in the Readme doesn't work? :smile:

**Comment by francislavoie** [comment]
Sure, but I'm also saying that this PR is not correct, because we're not using cpuid v2, yet. We had to downgrade to that version of cpuid because later versions broke compatibility on some platforms https://github.com/caddyserver/caddy/issues/3537

**Comment by cryptopragmatic** [comment]
It's not about PR, it's about the issue, which still persists. So, should I open an issue?

**Comment by francislavoie** [comment]
There was already an issue #112 but not enough information was given to show that there was a problem. We can probably re-open that one. I'll defer to @mholt though, it's not my decision to make.

**Comment by cryptopragmatic** [comment]
I'm programming with go for years and I've just got familiar with modules and I'm sure I'm not the only one.

go mod init, I've heard for it for the first time in my life. ALL other libraries work with only go get, I've never had an issue like this before in which I had to use the modules. And I said that admittedly, I'm not familiar with that modules mess they did.

**Comment by cryptopragmatic** [comment]
In my opinion, it would be just enough to add go mod init in the Readme, that way we can all start giving more attention to it.

**Comment by francislavoie** [comment]
> I'm programming with go for years and I've just got familiar with modules and I'm sure I'm not the only one.

> go mod init, I've heard for it for the first time in my life. ALL other libraries work with only go get, I've never had an issue like this before in which I had to use the modules. And I said that admittedly, I'm not familiar with that modules mess they did.

Honestly, I don't like your attitude. Open source is a collaboration. Please stick to the facts and calm down. Let's focus on the problem. Your tone only caused more frustration than necessary.

**Comment by cryptopragmatic** [comment]
Sorry, my frustration comes from the fact that I explicitly said how to reproduce the issue 4-5 times and you're constantly telling me the problem is on my side even though the issue was obviously discovered before. My code stopped working because of this and it's a production code.

**Comment by mholt** [comment]
Ugh. I'm just waking up to this.

@cryptopragmatic CertMagic _does_ work. Its code compiles and is used by thousands of servers around the world. The CI tests are proof. Sorry, but something about YOUR setup is wrong.

Your attitude is not welcome here, so I'm locking this thread. Abuse is not tolerated. If you decide to contribute again, please do so more nicely and put some effort in to explain your change without sharpness.

**Pull request closed without merging**
